# Author : S.A.
# January 13, 2011
import time
import glob
import re


def main():
    
    classList_FileName,iClickerNameList = findNames()
    
    classList = generate_classList(classList_FileName)

    process_iClicker_data(iClickerNameList,classList)

# gets filenames of files needed    
def findNames():
    lst = glob.glob('./*.csv')
    
    fileList = []

    for j in lst:
        
        if '.\ClassList.csv' == j :  #finds the classList csv downloaded from avenue
            classListN = j
            
        if re.match('.*(upload|Upload|UPLOAD).*',j):# finds all the uploadfiles.csv generated by igrader
            fileList.append(j)

    return classListN,fileList


#Generate the Dictionary record from a .csv file exported from Avenue
def generate_classList(fileName):
    classList = {}  #where all id and data will be held

    infile = open(fileName,'r')
    raw_data = infile.read()
    infile.close()

    data = raw_data.split('\n')
    data.remove(data[0])
    data.remove(data[-1])

    for line in data:
        
        eachline = line.split(',')
        classList[eachline[0]] = 0  #making the dictionary with each ID from classList.csv

    return classList
    

#Read iClicker Data file and add Attendance Data to Dictionary
def process_iClicker_data(nameList,classList):
    for name in nameList :
        currentFile = open(name,'r')
        data = currentFile.read().split('\n')
        currentFile.close()
        
        headers = data.pop(0)
        data.remove(data[-1])
        # goes through each file,and add the total mark of attendance to each ID
        for line in data:
            
            eachLine= line.split(',')
            try:
                classList[eachLine[0]] += int(eachLine[1])
                    
            except: #incase the ID doesn't exist (e.g. student dropped the course)
                continue
                
                
            
        

    make_CSV(classList)

    
#Write out Final Data into an Avenue Compatible .csv file
def make_CSV(classList):
    fileName = "Total_Attendance_"+ str(time.time())+".csv"

    outfile = open(fileName,'w')
    
    outfile.write('\xef\xbb\xbfUsername,Tutorial Attendance Points Grade <Numeric MaxPoints:11>,End-of-Line Indicator\n')

    for key in classList:                  
                  data = str(key)+','+str(classList[key])+',#\n'

                  outfile.write(data)

    outfile.close()



